In [2]:
import numpy as np
import pandas as pd 

samData = pd.read_csv("/qbio/nest/prom317/tutorial/transcriptomeAlignment/RPF_siLuc/ForwardStrand.out.sam", sep = '\t', names=['qname', 'flag', 'rname', 'pos', 'mapq', 'cigar', 'rnext', 'pnext', 'tlen', 'seq', 'qual','opt1', 'opt2', 'opt3', 'opt4'])
samData.head()

,qname,flag,rname,pos,mapq,cigar,rnext,pnext,tlen,seq,qual,opt1,opt2,opt3,opt4
0,SRR458756.2.803,0,ENSMUST00000240377.1|ENSMUSG00000119584.1|OTTM...,295,255,15M,*,0,0,TGGTGACTCTAGATA,B@@@@AAAAAAAAAA,NH:i:1,HI:i:1,AS:i:14,nM:i:0
1,SRR458756.2.918,0,ENSMUST00000091752.5|ENSMUSG00000069310.5|OTTM...,100,255,30M,*,0,0,CCAAGAATGGCTGGTACTAAGCAGACCGCT,A@A@@@A@@@?*.56A<2A<+;?*A??*?8,NH:i:1,HI:i:1,AS:i:27,nM:i:1
2,SRR458756.2.919,0,ENSMUST00000240377.1|ENSMUSG00000119584.1|OTTM...,815,255,28M,*,0,0,AAAAAATTAGAGTGTTCAAAGCAGGCCC,IIIIIIIHIHGGBG8AFFFFDGGBBGGG,NH:i:1,HI:i:1,AS:i:27,nM:i:0
3,SRR458756.2.922,0,ENSMUST00000240377.1|ENSMUSG00000119584.1|OTTM...,292,255,30M,*,0,0,CTTTGGCGACTCTAGATAACCTCGGGCCGA,##############################,NH:i:1,HI:i:1,AS:i:27,nM:i:1
4,SRR458756.2.923,0,ENSMUST00000023741.16|ENSMUSG00000048154.18|OT...,4117,3,1S17M,*,0,0,AGTGGCTGATATTGATAG,FC?BCGGGBBGEG@GDG>,NH:i:2,HI:i:1,AS:i:16,nM:i:0

In [3]:
samData['transcript_id'] = samData.rname.map(lambda p : p.split('|')[0])
samData['gene_id'] = samData.rname.map(lambda p : p.split('|')[1])
print(samData.shape)
samData.head()

(43076098, 17)

,qname,flag,rname,pos,mapq,cigar,rnext,pnext,tlen,seq,qual,opt1,opt2,opt3,opt4,transcript_id,gene_id
0,SRR458756.2.803,0,ENSMUST00000240377.1|ENSMUSG00000119584.1|OTTM...,295,255,15M,*,0,0,TGGTGACTCTAGATA,B@@@@AAAAAAAAAA,NH:i:1,HI:i:1,AS:i:14,nM:i:0,ENSMUST00000240377.1,ENSMUSG00000119584.1
1,SRR458756.2.918,0,ENSMUST00000091752.5|ENSMUSG00000069310.5|OTTM...,100,255,30M,*,0,0,CCAAGAATGGCTGGTACTAAGCAGACCGCT,A@A@@@A@@@?*.56A<2A<+;?*A??*?8,NH:i:1,HI:i:1,AS:i:27,nM:i:1,ENSMUST00000091752.5,ENSMUSG00000069310.5
2,SRR458756.2.919,0,ENSMUST00000240377.1|ENSMUSG00000119584.1|OTTM...,815,255,28M,*,0,0,AAAAAATTAGAGTGTTCAAAGCAGGCCC,IIIIIIIHIHGGBG8AFFFFDGGBBGGG,NH:i:1,HI:i:1,AS:i:27,nM:i:0,ENSMUST00000240377.1,ENSMUSG00000119584.1
3,SRR458756.2.922,0,ENSMUST00000240377.1|ENSMUSG00000119584.1|OTTM...,292,255,30M,*,0,0,CTTTGGCGACTCTAGATAACCTCGGGCCGA,##############################,NH:i:1,HI:i:1,AS:i:27,nM:i:1,ENSMUST00000240377.1,ENSMUSG00000119584.1
4,SRR458756.2.923,0,ENSMUST00000023741.16|ENSMUSG00000048154.18|OT...,4117,3,1S17M,*,0,0,AGTGGCTGATATTGATAG,FC?BCGGGBBGEG@GDG>,NH:i:2,HI:i:1,AS:i:16,nM:i:0,ENSMUST00000023741.16,ENSMUSG00000048154.18

In [4]:
gtfData = pd.read_table("/qbio/nest/prom317/tutorial/references/GRCm39.genome.gtf", sep = '\t', names = ["seq_name","source","feature","start","end","score","strand","frame","attribute"])
gtfData.iloc[5:10]

,seq_name,source,feature,start,end,score,strand,frame,attribute
5,chr1,HAVANA,gene,3143476.0,3144545.0,.,+,.,"gene_id ""ENSMUSG00000102693.2""; gene_type ""TEC..."
6,chr1,HAVANA,transcript,3143476.0,3144545.0,.,+,.,"gene_id ""ENSMUSG00000102693.2""; transcript_id ..."
7,chr1,HAVANA,exon,3143476.0,3144545.0,.,+,.,"gene_id ""ENSMUSG00000102693.2""; transcript_id ..."
8,chr1,ENSEMBL,gene,3172239.0,3172348.0,.,+,.,"gene_id ""ENSMUSG00000064842.3""; gene_type ""snR..."
9,chr1,ENSEMBL,transcript,3172239.0,3172348.0,.,+,.,"gene_id ""ENSMUSG00000064842.3""; transcript_id ..."

In [5]:
samData['start_pos'] = np.nan
samData['end_pos'] = np.nan
samData.head()

,qname,flag,rname,pos,mapq,cigar,rnext,pnext,tlen,seq,qual,opt1,opt2,opt3,opt4,transcript_id,gene_id,start_pos,end_pos
0,SRR458756.2.803,0,ENSMUST00000240377.1|ENSMUSG00000119584.1|OTTM...,295,255,15M,*,0,0,TGGTGACTCTAGATA,B@@@@AAAAAAAAAA,NH:i:1,HI:i:1,AS:i:14,nM:i:0,ENSMUST00000240377.1,ENSMUSG00000119584.1,NaN,NaN
1,SRR458756.2.918,0,ENSMUST00000091752.5|ENSMUSG00000069310.5|OTTM...,100,255,30M,*,0,0,CCAAGAATGGCTGGTACTAAGCAGACCGCT,A@A@@@A@@@?*.56A<2A<+;?*A??*?8,NH:i:1,HI:i:1,AS:i:27,nM:i:1,ENSMUST00000091752.5,ENSMUSG00000069310.5,NaN,NaN
2,SRR458756.2.919,0,ENSMUST00000240377.1|ENSMUSG00000119584.1|OTTM...,815,255,28M,*,0,0,AAAAAATTAGAGTGTTCAAAGCAGGCCC,IIIIIIIHIHGGBG8AFFFFDGGBBGGG,NH:i:1,HI:i:1,AS:i:27,nM:i:0,ENSMUST00000240377.1,ENSMUSG00000119584.1,NaN,NaN
3,SRR458756.2.922,0,ENSMUST00000240377.1|ENSMUSG00000119584.1|OTTM...,292,255,30M,*,0,0,CTTTGGCGACTCTAGATAACCTCGGGCCGA,##############################,NH:i:1,HI:i:1,AS:i:27,nM:i:1,ENSMUST00000240377.1,ENSMUSG00000119584.1,NaN,NaN
4,SRR458756.2.923,0,ENSMUST00000023741.16|ENSMUSG00000048154.18|OT...,4117,3,1S17M,*,0,0,AGTGGCTGATATTGATAG,FC?BCGGGBBGEG@GDG>,NH:i:2,HI:i:1,AS:i:16,nM:i:0,ENSMUST00000023741.16,ENSMUSG00000048154.18,NaN,NaN

In [6]:
gtfPlusData = gtfData.loc[gtfData.strand == "+"]
del gtfData
gtfPlusData['gene_id'] = gtfPlusData.attribute.map(lambda p: p.split(';')[0].split(' ')[1][1:-1])
gtfPlusData.gene_id.value_counts()

ENSMUSG00000052613.17    2003
ENSMUSG00000069601.15    1772
ENSMUSG00000021843.18    1695
ENSMUSG00000033788.16    1411
ENSMUSG00000064302.14    1411
                         ...
ENSMUSG00000107199.2        3
ENSMUSG00000098293.3        3
ENSMUSG00000109837.2        3
ENSMUSG00000077603.3        3
ENSMUSG00000095779.3        3
Name: gene_id, Length: 26876, dtype: int64

In [7]:
transcript_list = samData['transcript_id'].unique()
transDict = {}
for ts in transcript_list:
    transDict[ts] = [[],[]]
print(transcript_list)

['ENSMUST00000240377.1' 'ENSMUST00000091752.5' 'ENSMUST00000023741.16' ...
 'ENSMUST00000141667.2' 'ENSMUST00000099986.3' 'ENSMUST00000225350.2']

In [8]:
gtfExonData = gtfPlusData.loc[gtfPlusData.feature == 'exon']
gtfExonData["transcript_id"] = gtfExonData.iloc[:,8].map(lambda p: p.split(';')[1].split(' ')[2][1:-1])
gtfStartData = gtfPlusData.loc[gtfPlusData.feature == 'start_codon']
gtfStartData["transcript_id"] = gtfStartData.iloc[:,8].map(lambda p: p.split(';')[1].split(' ')[2][1:-1])
gtfStopData = gtfPlusData.loc[gtfPlusData.feature == 'stop_codon']
gtfStopData["transcript_id"] = gtfStopData.iloc[:,8].map(lambda p: p.split(';')[1].split(' ')[2][1:-1])
del gtfPlusData
gtfStartData.head()

/blaze/prom317/conda/envs/lab/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/blaze/prom317/conda/envs/lab/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/blaze/prom317/conda/envs/lab/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,seq_name,source,feature,start,end,score,strand,frame,attribute,gene_id,transcript_id
361,chr1,HAVANA,start_codon,4878137.0,4878139.0,.,+,0,"gene_id ""ENSMUSG00000025903.15""; transcript_id...",ENSMUSG00000025903.15,ENSMUST00000134384.8
386,chr1,HAVANA,start_codon,4878137.0,4878139.0,.,+,0,"gene_id ""ENSMUSG00000025903.15""; transcript_id...",ENSMUSG00000025903.15,ENSMUST00000027036.11
409,chr1,HAVANA,start_codon,4878137.0,4878139.0,.,+,0,"gene_id ""ENSMUSG00000025903.15""; transcript_id...",ENSMUSG00000025903.15,ENSMUST00000150971.8
430,chr1,HAVANA,start_codon,4878137.0,4878139.0,.,+,0,"gene_id ""ENSMUSG00000025903.15""; transcript_id...",ENSMUSG00000025903.15,ENSMUST00000119612.9
449,chr1,HAVANA,start_codon,4878137.0,4878139.0,.,+,0,"gene_id ""ENSMUSG00000025903.15""; transcript_id...",ENSMUSG00000025903.15,ENSMUST00000137887.8

In [9]:
count = 0
for ts in transDict.keys():
    count += 1
    if count % 1000 == 0:
        print(count)
    tsGtfExon = gtfExonData.loc[gtfExonData.transcript_id == ts]
    tsGtfStart = gtfStartData.loc[gtfStartData.transcript_id == ts]
    tsGtfStop = gtfStopData.loc[gtfStopData.transcript_id == ts]
    for idx, row in tsGtfExon.iterrows():
        transDict[ts][0].append(row['start'])
        transDict[ts][1].append(row['end'])
    if not (tsGtfStart.empty):
        transDict[ts].append(['start_codon',tsGtfStart.iloc[0,3]] )
    if not (tsGtfStop.empty):
        transDict[ts].append(['stop_codon',tsGtfStop.iloc[0,3]] )

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000

In [10]:
codingTransDict = {}
for i in transDict.keys():
    if len(transDict[i]) == 4:
        codingTransDict[i] = transDict[i]
print(len(codingTransDict))

21605

In [11]:
for i in codingTransDict.keys():
    exonStart = codingTransDict[i][0]
    exonEnd = codingTransDict[i][1]
    startCod = codingTransDict[i][2][1]
    stopCod = codingTransDict[i][3][1]
    exonLength = 0
    startPos = 0
    stopPos = 0
    for j in range(len(exonStart)):
        if exonStart[j] <= startCod < exonEnd[j]:
            startPos = exonLength + startCod - exonStart[j] + 1
            exonLength = exonLength + exonEnd[j] - exonStart[j] + 1
        elif exonStart[j] <= stopCod < exonEnd[j]:
            stopPos = exonLength + stopCod - exonStart[j] + 1
            exonLength = exonLength + exonEnd[j] - exonStart[j] + 1
        else:
            exonLength = exonLength + exonEnd[j] - exonStart[j] + 1
    codingTransDict[i].append(exonLength)
    codingTransDict[i].append(startPos)
    codingTransDict[i].append(stopPos)

In [12]:
codingDF = pd.DataFrame.from_dict(codingTransDict, orient = 'index')
codingDF.head()

,0,1,2,3,4,5,6
ENSMUST00000057000.17,"[98713242.0, 98713739.0, 98719037.0, 98722444....","[98713417.0, 98713781.0, 98719151.0, 98722484....","[start_codon, 98713382.0]","[stop_codon, 98752838.0]",3046.0,141.0,1878.0
ENSMUST00000110105.10,"[98713248.0, 98713739.0, 98719037.0, 98722444....","[98713417.0, 98713781.0, 98719151.0, 98722484....","[start_codon, 98713382.0]","[stop_codon, 98752838.0]",3514.0,135.0,2340.0
ENSMUST00000110104.10,"[98713223.0, 98713739.0, 98719037.0, 98722444....","[98713417.0, 98713781.0, 98719151.0, 98722484....","[start_codon, 98713382.0]","[stop_codon, 98752838.0]",3146.0,160.0,1972.0
ENSMUST00000067664.10,"[75623695.0, 75642707.0, 75646400.0, 75647643....","[75623917.0, 75642906.0, 75646506.0, 75647849....","[start_codon, 75623854.0]","[stop_codon, 75655496.0]",2100.0,160.0,925.0
ENSMUST00000041042.13,"[4136789.0, 4155757.0, 4159926.0, 4162141.0, 4...","[4137099.0, 4155856.0, 4160033.0, 4162247.0, 4...","[start_codon, 4136789.0]","[stop_codon, 4165151.0]",1957.0,1.0,1603.0

In [14]:
count = 0
for i in range(43076098):
    count +=1
    if count % 100000 ==0:
        print(count)
    if samData.iloc[i,15] in codingTransDict.keys():
        samData.iloc[i, 17] =1

KeyboardInterrupt:

In [24]:
for idx1, row1 in samData.iterrows():
    count +=1
    if count % 1000 == 0:
        print(count)
    try:
        row2 = codingDF.loc[row1[15]]
        pos = samData.loc[loc, 'pos']
        samData.loc[idx, 'start_pos'] = pos - row2[5] 
        samData.loc[idx, 'end_pos'] = pos - row2[6]
    except KeyError:
        continue
samData.head()

KeyboardInterrupt:

In [ ]:
samData = samData.loc[samData.start_pos.notnull()]

In [25]:
gtfTranscriptData["transcript_id"] = gtfTranscriptData.iloc[:,8].map(lambda p: p.split(';')[1].split(' ')[2][1:-1])
gtfTranscriptData = gtfTranscriptData.set_index('transcript_id')
gtfTranscriptData.head()

,0,1,2,3,4,5,6,7,8
transcript_id,,,,,,,,,
ENSMUST00000193812.2,chr1,HAVANA,transcript,3143476.0,3144545.0,.,+,.,"gene_id ""ENSMUSG00000102693.2""; transcript_id ..."
ENSMUST00000082908.3,chr1,ENSEMBL,transcript,3172239.0,3172348.0,.,+,.,"gene_id ""ENSMUSG00000064842.3""; transcript_id ..."
ENSMUST00000162897.2,chr1,HAVANA,transcript,3276124.0,3286567.0,.,-,.,"gene_id ""ENSMUSG00000051951.6""; transcript_id ..."
ENSMUST00000159265.2,chr1,HAVANA,transcript,3276746.0,3285855.0,.,-,.,"gene_id ""ENSMUSG00000051951.6""; transcript_id ..."
ENSMUST00000070533.5,chr1,HAVANA,transcript,3284705.0,3741721.0,.,-,.,"gene_id ""ENSMUSG00000051951.6""; transcript_id ..."

In [35]:
count = 0
samData['distance'] = np.nan
for idx1, row1 in samData.iterrows():
    if count % 10000 == 0:
        print(count)
    try:
        row2 = gtfTranscriptData.loc[row1[2]]
        samData.loc[idx1,'distance'] = 78387934 - (row2[4]-row1[3]+1)
        count = count +1
    except KeyError:
        if count %10000 == 0:
            print('Error')
        continue
samData.head()

0
10000
20000
30000
40000
50000
60000
70000
80000
90000
100000
110000
120000
130000
140000
150000
160000
170000
180000
190000
200000
210000
220000
230000
240000
250000
260000
270000
280000
290000
300000
310000
320000
330000
340000
350000
360000
370000

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,distance
0,SRR458756.2.1104,0,ENSMUST00000129380.2,117,1,30M,*,0,0,CGAGTGGAGACTGGTGTTCTCAAGCCTGGC,IIIIIIIIIIIIIIIIIIGIIIIIIIIIIH,NH:i:4,HI:i:1,AS:i:29,nM:i:0,1052.0
1,SRR458756.2.1104,256,ENSMUST00000042235.15,916,1,30M,*,0,0,CGAGTGGAGACTGGTGTTCTCAAGCCTGGC,IIIIIIIIIIIIIIIIIIGIIIIIIIIIIH,NH:i:4,HI:i:2,AS:i:29,nM:i:0,-157.0
2,SRR458756.2.1104,256,ENSMUST00000144523.8,919,1,30M,*,0,0,CGAGTGGAGACTGGTGTTCTCAAGCCTGGC,IIIIIIIIIIIIIIIIIIGIIIIIIIIIIH,NH:i:4,HI:i:3,AS:i:29,nM:i:0,882.0
3,SRR458756.2.1104,256,ENSMUST00000150960.2,823,1,30M,*,0,0,CGAGTGGAGACTGGTGTTCTCAAGCCTGGC,IIIIIIIIIIIIIIIIIIGIIIIIIIIIIH,NH:i:4,HI:i:4,AS:i:29,nM:i:0,975.0
4,SRR458756.2.1167,256,ENSMUST00000042235.15,1390,0,32M,*,0,0,TTTGCTGTTCGTGACATGAGGCAGACAGTTGC,IIIIIIIIIIIIIIIIIIHIIIIDIIIBIIHG,NH:i:7,HI:i:3,AS:i:31,nM:i:0,317.0

In [36]:
samData_drop = samData.loc[samData.distance.notnull()]

In [37]:
samData_drop.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,distance
0,SRR458756.2.1104,0,ENSMUST00000129380.2,117,1,30M,*,0,0,CGAGTGGAGACTGGTGTTCTCAAGCCTGGC,IIIIIIIIIIIIIIIIIIGIIIIIIIIIIH,NH:i:4,HI:i:1,AS:i:29,nM:i:0,1052.0
1,SRR458756.2.1104,256,ENSMUST00000042235.15,916,1,30M,*,0,0,CGAGTGGAGACTGGTGTTCTCAAGCCTGGC,IIIIIIIIIIIIIIIIIIGIIIIIIIIIIH,NH:i:4,HI:i:2,AS:i:29,nM:i:0,-157.0
2,SRR458756.2.1104,256,ENSMUST00000144523.8,919,1,30M,*,0,0,CGAGTGGAGACTGGTGTTCTCAAGCCTGGC,IIIIIIIIIIIIIIIIIIGIIIIIIIIIIH,NH:i:4,HI:i:3,AS:i:29,nM:i:0,882.0
3,SRR458756.2.1104,256,ENSMUST00000150960.2,823,1,30M,*,0,0,CGAGTGGAGACTGGTGTTCTCAAGCCTGGC,IIIIIIIIIIIIIIIIIIGIIIIIIIIIIH,NH:i:4,HI:i:4,AS:i:29,nM:i:0,975.0
4,SRR458756.2.1167,256,ENSMUST00000042235.15,1390,0,32M,*,0,0,TTTGCTGTTCGTGACATGAGGCAGACAGTTGC,IIIIIIIIIIIIIIIIIIHIIIIDIIIBIIHG,NH:i:7,HI:i:3,AS:i:31,nM:i:0,317.0